[workspace.package]
repository = "https://github.com/zigbee-rs"
readme = "README.md"
edition = "2024"
license = "CC-BY-NC-SA-4.0"
categories = ["network-programming", "no-std", "embedded"]

[workspace]
members = [
    "zb-hal-esp32",
    "examples/esp-device"
]
default-members = [
    "zb-hal-esp32",
]

resolver = "3"

[workspace.dependencies]
bon = { version = "3.9.3", default-features = false }
byte = { version = "0.2.7", default-features = false }

embassy-executor = { version = "0.10.0", default-features = false }
embassy-futures = { version = "0.1.2", default-features = false }
embassy-sync = { version = "0.8.0", default-features = false }
embassy-time = { version = "0.5.0", default-features = false }

embedded-storage = { version = "0.3.1", default-features = false }
esp-bootloader-esp-idf = { version = "0.5.0", default-features = false }
esp-hal = { version = "1.1.1", default-features = false, features = ["log-04"] }
esp-radio = { version = "0.18.0", default-features = false, features = ["ieee802154", "unstable"] }
esp-storage = { version = "0.9.0", default-features = false }

heapless = { version = "0.9.1", default-features = false, features = ["bytes"] }
ieee802154 = { version = "0.6.1", default-features = false }
itertools = { version = "0.15.0", default-features = false }
log = { version = "0.4.29", default-features = false }

zb-hal = { path = "./../common/zb-hal", version = "0.1.0" }
zb-types = { path = "./../common/zb-types", version = "0.1.0" }
zb-rs = { path = "../common/zb-rs", version = "0.1.0" }
zb-macros = { path = "./../common/zb-macros", version = "0.1.0" }
zb-zcl-clusters = { path = "./../common/zb-zcl-clusters", version = "0.1.0" }

[profile.release]
lto              = "fat"
codegen-units    = 1

[profile.release.package.esp-device]
debug            = "full"
debug-assertions = true
