use zb_types::mac::A_MAX_PHY_PACKET_SIZE;

pub const A_BASE_SLOT_DURATION: u32 = 60;
pub const A_BASE_SUPER_FRAME_DURATION: u32 = A_BASE_SLOT_DURATION * A_NUM_SUPER_FRAME_SLOTS;
pub const A_GTS_DESC_PERSISTENCE_TIME: u8 = 4;
pub const A_MAX_BEACON_OVERHEAD: usize = 75;
pub const A_MAX_BEACON_PAYLOAD_LENGTH: usize = A_MAX_PHY_PACKET_SIZE - A_MAX_BEACON_OVERHEAD;
pub const A_MAX_LOST_BEACONS: u8 = 4;

pub const A_MAX_SIFSF_FRAME_SIZE: usize = 18;
pub const A_MIN_CAP_LENGTH: u16 = 440;
pub const A_NUM_SUPER_FRAME_SLOTS: u32 = 16;
pub const A_UNIT_BACKOFF_PERIOD: u8 = 20;

pub const MAX_IEEE802154_CHANNELS: usize = 27;

pub const MAX_PAN_DESCRIPTOR_SIZE: usize = 27;

pub const A_MAX_FRAME_RESPONSE_TIME: u32 = 1220;
pub const A_MAX_FRAME_RETRIES: u32 = 3;
pub const A_MAX_LOST_FRAMES: u32 = 4;
pub const A_RESPONSE_WAIT_TIME: u32 = 32 * A_BASE_SUPER_FRAME_DURATION;
